# name: Publish to PyPI
# on:
#   push:
#     tags:
#       - "v*"
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.9'
#     - name: Install dependencies
#       run: pip install pytest
#     - name: Run tests
#       run: pytest

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: ${{ job.status == 'success' }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.9'
  #   - name: Install Poetry
  #     run: |
  #       pip install poetry
  #   - name: Authenticate with PyPI
  #     env:
  #       TWINE_USERNAME: __token__
  #       TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  #     run: echo "machine pypi.org login __token__ password $TWINE_PASSWORD" > ~/.pypirc
  #   - name: Publish to PyPI
  #     run: |
  #       poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
