name: Python Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipx
      run: python -m pip install --upgrade pip pipx

    - name: Install Poetry via pipx
      run: pipx install poetry
    
    - name: Set virtualenv location
      run: poetry config virtualenvs.in-project true
    
    - name: Verify poetry.lock is up to date
      run: poetry lock --check

    - name: Install dependencies
      run: poetry install --with dev

    - name: Run black
      run: poetry run black --check .

    - name: Run pytest
      run: poetry run pytest
